<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step?,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*,Summary,ActionMaintenanceSummary*,NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?)>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="中国标准时间">
<General productName="QuickTest Professional" productVer="10.00" os="Windows XP" host="KEADIN-49F907A9"><DocLocation><![CDATA[C:\DOCUME~1\Keadin\LOCALS~1\Temp\~tlp3\~Test1]]></DocLocation></General>
<Doc rID="T1"   productName= "QuickTest Professional"  >
<DName><![CDATA[Test]]></DName>
<Res><![CDATA[Res1]]></Res>
<DT rID="T2">
<NodeArgs eType="Table" icon="2" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table">
<Path><![CDATA[Default.xls]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<DIter rID="T3" iterID="1" >
<Step rID="T4">
<Obj plainTxt="False" ><![CDATA[StartUp Browser]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[2018-6-25 - 16:09:26]]></Time>
<TimeTick>1529914166</TimeTick>
<Step rID="T5">
<Obj plainTxt="False" ><![CDATA[StartUp Browser]]></Obj>
<Details plainTxt="False" ><![CDATA[Navigate to www.zuccyanghaha.cn]]></Details>
<Time><![CDATA[2018-6-25 - 16:09:26]]></Time>
<TimeTick>1529914166</TimeTick>
<NodeArgs eType="Replay" icon="4" nRep="9" nType="Navigate to www.zuccyanghaha.cn" Source="Action0" SourceLine="-1" >
<Disp><![CDATA[StartUp Browser]]></Disp>
</NodeArgs>
</Step>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA[StartUp Browser.Sync]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2018-6-25 - 16:09:32]]></Time>
<TimeTick>1529914172</TimeTick>
<NodeArgs eType="Replay" icon="4" nRep="11" Source="Action0" SourceLine="-1" >
<Disp><![CDATA[StartUp Browser.Sync]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="4" nRep="8" Source="Action0" SourceLine="-1" >
<Disp><![CDATA[StartUp Browser]]></Disp>
</NodeArgs>
</Step>
<Action rID="T7">
<AName><![CDATA[Action1]]></AName>
<Step rID="T8">
<Obj plainTxt="False" ><![CDATA[Browser]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[2018-6-25 - 16:09:32]]></Time>
<TimeTick>1529914172</TimeTick>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[Page]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[2018-6-25 - 16:09:32]]></Time>
<TimeTick>1529914172</TimeTick>
<Step rID="T10">
<Obj plainTxt="False" ><![CDATA[首页.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2018-6-25 - 16:09:32]]></Time>
<TimeTick>1529914172</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="17" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[首页.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA[学习生活.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2018-6-25 - 16:09:36]]></Time>
<TimeTick>1529914176</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="23" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[学习生活.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="16" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Page]]></Disp>
</NodeArgs>
</Step>
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA[Page_2]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[2018-6-25 - 16:09:38]]></Time>
<TimeTick>1529914178</TimeTick>
<Step rID="T13">
<Obj plainTxt="False" ><![CDATA[t2.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2018-6-25 - 16:09:38]]></Time>
<TimeTick>1529914178</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="27" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[t2.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="26" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Page_2]]></Disp>
</NodeArgs>
</Step>
<Step rID="T14">
<Obj plainTxt="False" ><![CDATA[Page_3]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[2018-6-25 - 16:09:40]]></Time>
<TimeTick>1529914180</TimeTick>
<Step rID="T15">
<Obj plainTxt="False" ><![CDATA["首页"- Smart Identification]]></Obj>
<Details plainTxt="False" ><![CDATA[<P><span class="text">The smart identification mechanism was invoked.</span></P><P><SPAN class=text>Reason: object not unique (2 objects found)</SPAN></P>           <SPAN class=text><b>Original description:</b></SPAN><br>text=首页<br>micclass=Link<br>html tag=A<br><P><FONT face=Verdana size=2><SPAN class=text><B>Smart Identification Alternative Description: </B></SPAN></FONT></P><FONT face=Verdana size=2><u>Base filter properties (11 objects found)&nbsp;</FONT></u><br>
micclass=Link<br>html tag=A<br><br><FONT face=Verdana size=2><u>Optional filter properties</FONT></u><br>
text=首页<SPAN class=passed> (Used</SPAN>, 2 matches)</SPAN><br>html id=<SPAN class=passed> (Used</SPAN>, 2 matches)</SPAN><br>class=navbar-brand<SPAN class=passed> (Used</SPAN>, 1 matches)</SPAN><br>name=首页<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>href=http://www.zuccyanghaha.cn/<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>visible=1<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>]]></Details>
<Time><![CDATA[2018-6-25 - 16:09:40]]></Time>
<TimeTick>1529914180</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="31" Source="Action1" SourceLine="-1" >
<Disp><![CDATA["首页"- Smart Identification]]></Disp>
</NodeArgs>
</Step>
<Step rID="T16">
<Obj plainTxt="False" ><![CDATA[首页.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2018-6-25 - 16:09:40]]></Time>
<TimeTick>1529914180</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="32" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[首页.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="30" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Page_3]]></Disp>
</NodeArgs>
</Step>
<Step rID="T17">
<Obj plainTxt="False" ><![CDATA[Page]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[2018-6-25 - 16:09:43]]></Time>
<TimeTick>1529914183</TimeTick>
<Step rID="T18">
<Obj plainTxt="False" ><![CDATA[搜索.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2018-6-25 - 16:09:43]]></Time>
<TimeTick>1529914183</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="36" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[搜索.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="35" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Page]]></Disp>
</NodeArgs>
</Step>
<Step rID="T19">
<Obj plainTxt="False" ><![CDATA[Page_4]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[2018-6-25 - 16:09:45]]></Time>
<TimeTick>1529914185</TimeTick>
<Step rID="T20">
<Obj plainTxt="False" ><![CDATA[注册/登录.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2018-6-25 - 16:09:45]]></Time>
<TimeTick>1529914185</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="40" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[注册/登录.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T21">
<Obj plainTxt="False" ><![CDATA[UID.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["31601418"]]></Details>
<Time><![CDATA[2018-6-25 - 16:09:47]]></Time>
<TimeTick>1529914187</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="43" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[UID.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T22">
<Obj plainTxt="False" ><![CDATA[password.SetSecure]]></Obj>
<Details plainTxt="False" ><![CDATA["5b30a2fa53f886cd05b6528b8f2f8e9052431e9ccdab"]]></Details>
<Time><![CDATA[2018-6-25 - 16:09:47]]></Time>
<TimeTick>1529914187</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="46" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[password.SetSecure]]></Disp>
</NodeArgs>
</Step>
<Step rID="T23">
<Obj plainTxt="False" ><![CDATA[登 录.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2018-6-25 - 16:09:47]]></Time>
<TimeTick>1529914187</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="49" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[登 录.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="39" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Page_4]]></Disp>
</NodeArgs>
</Step>
<Step rID="T24">
<Obj plainTxt="False" ><![CDATA[Page]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[2018-6-25 - 16:09:52]]></Time>
<TimeTick>1529914192</TimeTick>
<Step rID="T25">
<Obj plainTxt="False" ><![CDATA[学习生活.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2018-6-25 - 16:09:52]]></Time>
<TimeTick>1529914192</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="53" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[学习生活.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="52" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Page]]></Disp>
</NodeArgs>
</Step>
<Step rID="T26">
<Obj plainTxt="False" ><![CDATA[Page_2]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[2018-6-25 - 16:09:57]]></Time>
<TimeTick>1529914197</TimeTick>
<Step rID="T27">
<Obj plainTxt="False" ><![CDATA[考研交流>.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2018-6-25 - 16:09:57]]></Time>
<TimeTick>1529914197</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="57" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[考研交流>.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T28">
<Obj plainTxt="False" ><![CDATA["首页"- Smart Identification]]></Obj>
<Details plainTxt="False" ><![CDATA[<P><span class="text">The smart identification mechanism was invoked.</span></P><P><SPAN class=text>Reason: object not unique (2 objects found)</SPAN></P>           <SPAN class=text><b>Original description:</b></SPAN><br>text=首页<br>micclass=Link<br>html tag=A<br><P><FONT face=Verdana size=2><SPAN class=text><B>Smart Identification Alternative Description: </B></SPAN></FONT></P><FONT face=Verdana size=2><u>Base filter properties (17 objects found)&nbsp;</FONT></u><br>
micclass=Link<br>html tag=A<br><br><FONT face=Verdana size=2><u>Optional filter properties</FONT></u><br>
text=首页<SPAN class=passed> (Used</SPAN>, 2 matches)</SPAN><br>html id=<SPAN class=passed> (Used</SPAN>, 2 matches)</SPAN><br>class=navbar-brand<SPAN class=passed> (Used</SPAN>, 1 matches)</SPAN><br>name=首页<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>href=http://www.zuccyanghaha.cn/<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>visible=1<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>]]></Details>
<Time><![CDATA[2018-6-25 - 16:09:57]]></Time>
<TimeTick>1529914197</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="60" Source="Action1" SourceLine="-1" >
<Disp><![CDATA["首页"- Smart Identification]]></Disp>
</NodeArgs>
</Step>
<Step rID="T29">
<Obj plainTxt="False" ><![CDATA[首页.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2018-6-25 - 16:09:57]]></Time>
<TimeTick>1529914197</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="61" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[首页.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="56" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Page_2]]></Disp>
</NodeArgs>
</Step>
<Step rID="T30">
<Obj plainTxt="False" ><![CDATA[上一个站点可能需要下列ActiveX 控件:.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2018-6-25 - 16:10:24]]></Time>
<TimeTick>1529914224</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="67" status="Warning" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[上一个站点可能需要下列ActiveX 控件:.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T31">
<Obj plainTxt="False" ><![CDATA[上一个站点可能需要下列ActiveX 控件:]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot find the "上一个站点可能需要下列ActiveX 控件:" object's parent "Browser" (class Browser). Verify that parent properties match an object currently displayed in your application.]]></Details>
<Time><![CDATA[2018-6-25 - 16:10:24]]></Time>
<TimeTick>1529914224</TimeTick>
<Step rID="T32">
<Obj plainTxt="False" ><![CDATA[Browser]]></Obj>
<Details plainTxt="False" ><![CDATA[Object's physical description:<br>Mercury Class = Browser<br>CreationTime = 0<br>|Title = http://www.zuccyanghaha.cn/<br>openurl = http://www.zuccyanghaha.cn<br>opentitle = <br>Opened By Testing Tool = -1<br>number of tabs = 0<br>Name = <br>Has Toolbar = -1<br>Has Status Bar = -1<br>Has Menu Bar = -1<br>]]></Details>
<Time><![CDATA[2018-6-25 - 16:10:24]]></Time>
<TimeTick>1529914224</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="69" status="Warning" nType="Parent description" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Browser]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="11" nRep="68" status="Failed" nType="Run Error" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[上一个站点可能需要下列ActiveX 控件:]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="4" nRep="15" status="Failed" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Browser]]></Disp>
</NodeArgs>
</Step>
<Step rID="T33">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot find the &quot;上一个站点可能需要下列ActiveX 控件:&quot; object's parent &quot;Browser&quot; (class Browser). Verify that parent properties match an object currently displayed in your application.<BR>Line (1): &quot;Browser(&quot;Browser&quot;).Page(&quot;Page&quot;).Link(&quot;首页&quot;).Click&quot;. ]]></Details>
<Time><![CDATA[2018-6-25 - 16:10:24]]></Time>
<TimeTick>1529914224</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="70" status="Failed" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<Step rID="T34">
<Obj plainTxt="False" ><![CDATA[Stop Run]]></Obj>
<Details plainTxt="False" ><![CDATA[Run stopped by user.]]></Details>
<Time><![CDATA[2018-6-25 - 16:10:25]]></Time>
<TimeTick>1529914225</TimeTick>
<NodeArgs eType="General" icon="13" nRep="71" >
<Disp><![CDATA[Stop Run]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="2018-6-25 - 16:09:32" eTime="2018-6-25 - 16:10:25" passed="0" failed="2" warnings="2" ></Summary>
<NodeArgs eType="StartAction" icon="5" nRep="12" status="Failed" >
<Disp><![CDATA[Action1 Summary]]></Disp>
</NodeArgs>
</Action>
<NodeArgs eType="StartIteration" icon="3" nRep="6" status="Failed" >
<Disp><![CDATA[Test Iteration 1 (Row 1)]]></Disp>
</NodeArgs>
</DIter>
<Summary sTime="2018-6-25 - 16:09:25" eTime="2018-6-25 - 16:10:25" passed="0" failed="2" warnings="2" ></Summary>
<NodeArgs eType="StartTest" icon="1" nRep="3" status="Failed" >
<Disp><![CDATA[Test Test Summary]]></Disp>
</NodeArgs>
</Doc>
</Report>